import { useState } from 'react';
import { motion } from 'framer-motion';
import {
  Map, Clock, Copy, Printer,
  Download, Sparkles, HelpCircle, ArrowRight, Check, Target, Zap
} from 'lucide-react';
import { Link } from 'react-router-dom';
import { generateRoadmap } from '../services/api';
import type { RoadmapResult } from '../types';
import LoadingState from '../components/LoadingState';
import { AdBanner } from '../components/AnalysisComponents';
import { useSEO, buildFaqSchema } from '../lib/seo';

const CREATOR_STAGES = [
  'Just starting (0 subscribers)',
  'Beginner (1–500 subscribers)',
  'Growing (500–5K subscribers)',
  'Established (5K–50K subscribers)',
  'Scaling Creator (50K+ subscribers)',
];

const POSTING_FREQUENCIES = [
  '1 video per week',
  '2 videos per week',
  '3+ videos per week',
  'Daily Shorts',
  'Mix of Long-form & Shorts',
];

const PLATFORMS = ['YouTube (Primary)', 'YouTube + Shorts', 'TikTok & Shorts', 'Multi-Platform'];

const weekCardThemes = [
  { bg: 'from-blue-50/70 to-blue-100/30', border: 'border-blue-200', badge: 'bg-blue-100 text-blue-700' },
  { bg: 'from-purple-50/70 to-purple-100/30', border: 'border-purple-200', badge: 'bg-purple-100 text-purple-700' },
  { bg: 'from-green-50/70 to-green-100/30', border: 'border-green-200', badge: 'bg-green-100 text-green-700' },
  { bg: 'from-amber-50/70 to-amber-100/30', border: 'border-amber-200', badge: 'bg-amber-100 text-amber-700' },
];

const priorityBadges: Record<string, string> = {
  High: 'bg-red-50 text-red-700 border-red-200',
  Medium: 'bg-amber-50 text-amber-700 border-amber-200',
  Low: 'bg-blue-50 text-blue-700 border-blue-200',
};

const FAQ = [
  {
    q: 'How is the 30-Day Growth Roadmap customized?',
    a: 'TrendlyInside matches your current audience stage, upload frequency, and specific milestone goal against proven creator growth frameworks, prioritizing high-leverage actions week by week.',
  },
  {
    q: 'Can I print or export my roadmap to Notion?',
    a: 'Yes! Use the "Print" button for a clean print stylesheet, or "Copy Plan" / "Export Text" to paste directly into Notion, Google Docs, or Obsidian.',
  },
  {
    q: 'What is a success signal in each weekly milestone?',
    a: 'A success signal is an objective metric (such as a 12% click-through rate, a 45% retention average, or completing 3 batch recordings) that confirms you are on track.',
  },
  {
    q: 'Is this roadmap generator completely free?',
    a: 'Yes, 100% free with no login required.',
  },
];

export default function RoadmapGeneratorPage() {
  const [niche, setNiche] = useState('');
  const [currentStage, setCurrentStage] = useState(CREATOR_STAGES[1]);
  const [goal, setGoal] = useState('');
  const [postingFrequency, setPostingFrequency] = useState(POSTING_FREQUENCIES[1]);
  const [primaryPlatform, setPrimaryPlatform] = useState(PLATFORMS[0]);
  const [result, setResult] = useState<RoadmapResult | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');
  const [copied, setCopied] = useState(false);

  useSEO({
    title: 'Free 30-Day Creator Growth Roadmap Generator — Weekly Milestone AI',
    description: 'Build a customized 4-week YouTube growth roadmap with objectives, prioritized execution tasks, estimated effort, and milestone success signals.',
    path: '/growth-roadmap-generator',
    structuredData: buildFaqSchema(FAQ),
  });

  const handleGenerate = async () => {
    if (!niche.trim() || !goal.trim()) {
      setError('Please provide your niche and primary growth goal');
      return;
    }
    setIsLoading(true);
    setError('');
    setResult(null);
    try {
      const data = await generateRoadmap({
        niche: niche.trim(),
        currentStage,
        goal: `${goal.trim()} (Platform: ${primaryPlatform})`,
        postingFrequency,
      });
      setResult(data);
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Generation failed. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  const getExportText = () => {
    if (!result) return '';
    return `TrendlyInside 30-Day Growth Roadmap
=====================================
Plan: ${result.roadmapTitle}
Niche: ${result.niche}
Goal: ${result.goal}
Stage: ${currentStage}

OVERVIEW:
${result.overview}

${result.weeks
  .map(
    (w) => `WEEK ${w.week}: ${w.focus}
Theme: ${w.theme}
Tasks:
${w.tasks.map((t) => `• [${t.priority} Priority] ${t.task} (${t.timeEstimate})`).join('\n')}
Weekly Milestone: ${w.milestone}`
  )
  .join('\n\n')}

KEY METRICS TO TRACK:
${result.keyMetrics?.map((m) => `• ${m}`).join('\n') || ''}

SUCCESS TIP:
${result.successTip}

Generated by TrendlyInside — https://trendlyinside.com`;
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(getExportText());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportText = () => {
    if (!result) return;
    const blob = new Blob([getExportText()], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `30-Day-Growth-Roadmap-${result.niche.replace(/\s+/g, '-')}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <>
      <div
        className="pt-28 md:pt-32 pb-14 border-b border-glacial-sky/20"
        style={{ background: 'linear-gradient(135deg, #F7FAFC 0%, #E8F0F7 100%)' }}
      >
        <div className="container-main text-center">
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }}>
            <span className="badge-primary mb-3 inline-flex">30-Day Growth Engine</span>
            <h1 className="font-heading font-bold text-3xl md:text-5xl text-midnight-abyss mt-2 mb-3">
              Growth Roadmap Generator
            </h1>
            <p className="text-frosty-slate max-w-xl mx-auto mb-8 text-sm md:text-base leading-relaxed">
              Build a personalized 4-week milestone strategy tailored to your creator stage, posting schedule, and subscriber targets.
            </p>

            {/* Input Form */}
            <div className="w-full max-w-2xl mx-auto card p-6 text-left border-glacial-sky/35 shadow-card">
              <div className="space-y-4">
                <div>
                  <label htmlFor="roadmap-niche" className="block text-xs font-bold text-midnight-abyss uppercase tracking-wider mb-1.5">
                    Your Niche *
                  </label>
                  <input
                    id="roadmap-niche"
                    type="text"
                    value={niche}
                    onChange={(e) => {
                      setNiche(e.target.value);
                      if (error) setError('');
                    }}
                    placeholder="e.g. Personal Finance, Tech Reviews, Gaming, Productivity"
                    className="input-base"
                    disabled={isLoading}
                  />
                </div>

                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  <div>
                    <label className="block text-xs font-bold text-midnight-abyss uppercase tracking-wider mb-1.5">
                      Current Creator Stage
                    </label>
                    <select
                      value={currentStage}
                      onChange={(e) => setCurrentStage(e.target.value)}
                      className="input-base cursor-pointer"
                      disabled={isLoading}
                    >
                      {CREATOR_STAGES.map((s) => (
                        <option key={s} value={s}>{s}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-midnight-abyss uppercase tracking-wider mb-1.5">
                      Posting Cadence
                    </label>
                    <select
                      value={postingFrequency}
                      onChange={(e) => setPostingFrequency(e.target.value)}
                      className="input-base cursor-pointer"
                      disabled={isLoading}
                    >
                      {POSTING_FREQUENCIES.map((f) => (
                        <option key={f} value={f}>{f}</option>
                      ))}
                    </select>
                  </div>

                  <div>
                    <label className="block text-xs font-bold text-midnight-abyss uppercase tracking-wider mb-1.5">
                      Primary Platform
                    </label>
                    <select
                      value={primaryPlatform}
                      onChange={(e) => setPrimaryPlatform(e.target.value)}
                      className="input-base cursor-pointer"
                      disabled={isLoading}
                    >
                      {PLATFORMS.map((p) => (
                        <option key={p} value={p}>{p}</option>
                      ))}
                    </select>
                  </div>
                </div>

                <div>
                  <label htmlFor="roadmap-goal" className="block text-xs font-bold text-midnight-abyss uppercase tracking-wider mb-1.5">
                    Your 30-Day Primary Goal *
                  </label>
                  <input
                    id="roadmap-goal"
                    type="text"
                    value={goal}
                    onChange={(e) => {
                      setGoal(e.target.value);
                      if (error) setError('');
                    }}
                    onKeyDown={(e) => e.key === 'Enter' && handleGenerate()}
                    placeholder="e.g. Reach 5,000 subscribers and achieve a 50% average retention rate"
                    className="input-base"
                    disabled={isLoading}
                  />
                </div>

                {error && <p className="text-red-600 text-xs mt-1">{error}</p>}

                <button
                  onClick={handleGenerate}
                  disabled={isLoading}
                  className="btn-primary w-full py-3.5 text-sm md:text-base font-semibold shadow-btn mt-2 cursor-pointer"
                  id="generate-roadmap-btn"
                >
                  <Map className="w-4 h-4" />
                  <span>{isLoading ? 'Formulating 30-Day Plan...' : 'Generate 30-Day Growth Plan'}</span>
                </button>
              </div>
            </div>
          </motion.div>
        </div>
      </div>

      <div className="container-main py-10">
        {isLoading && (
          <LoadingState
            title="Building Your 30-Day Growth Strategy..."
            subtitle="Calculating weekly objectives, task priorities, and milestone benchmarks..."
            steps={[
              { label: 'Analyzing creator stage & posting bandwidth' },
              { label: 'Week 1: Optimization & First Impressions' },
              { label: 'Week 2: Retention & Packaging Overhaul' },
              { label: 'Week 3: Algorithmic Expansion & Momentum' },
              { label: 'Week 4: Monetization & Community Retention' },
            ]}
          />
        )}

        {result && !isLoading && (
          <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} className="space-y-8">
            {/* Roadmap Header Card */}
            <div className="card p-6 border-glacial-sky/35 bg-white">
              <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-glacial-sky/20">
                <div>
                  <span className="badge-primary text-xs mb-2 inline-flex">Custom 30-Day Plan</span>
                  <h2 className="font-heading font-bold text-2xl text-midnight-abyss">
                    {result.roadmapTitle}
                  </h2>
                  <p className="text-xs text-frosty-slate mt-1">
                    Niche: {result.niche} • Goal: {result.goal}
                  </p>
                </div>

                {/* Toolbar */}
                <div className="flex items-center gap-2 flex-wrap">
                  <button onClick={handleCopy} className="btn-secondary text-xs py-2 px-3">
                    {copied ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copied ? 'Plan Copied!' : 'Copy Plan'}</span>
                  </button>
                  <button onClick={handleExportText} className="btn-secondary text-xs py-2 px-3">
                    <Download className="w-3.5 h-3.5" />
                    <span>Export Text</span>
                  </button>
                  <button onClick={handlePrint} className="btn-secondary text-xs py-2 px-3">
                    <Printer className="w-3.5 h-3.5" />
                    <span>Print</span>
                  </button>
                </div>
              </div>

              <p className="text-sm text-midnight-abyss leading-relaxed mt-4 bg-glacial-sky/10 p-4 rounded-xl border border-glacial-sky/20">
                {result.overview}
              </p>
            </div>

            {/* Weekly Breakdown Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {result.weeks.map((weekData, idx) => {
                const theme = weekCardThemes[idx % weekCardThemes.length];
                return (
                  <div
                    key={weekData.week}
                    className={`card p-6 border bg-gradient-to-br ${theme.bg} ${theme.border} flex flex-col justify-between`}
                  >
                    <div>
                      <div className="flex items-center justify-between gap-2 mb-3">
                        <span className="w-8 h-8 rounded-xl bg-midnight-abyss/10 text-midnight-abyss font-bold text-xs flex items-center justify-center">
                          W{weekData.week}
                        </span>
                        <span className={`badge text-xs ${theme.badge}`}>
                          {weekData.theme}
                        </span>
                      </div>

                      <h3 className="font-heading font-bold text-lg text-midnight-abyss mb-3">
                        {weekData.focus}
                      </h3>

                      <div className="space-y-3 mb-4">
                        {weekData.tasks.map((task, ti) => (
                          <div
                            key={ti}
                            className="p-3 rounded-xl bg-white/80 border border-white/60 shadow-2xs flex items-start justify-between gap-2 text-xs"
                          >
                            <div className="flex items-start gap-2">
                              <span className="w-1.5 h-1.5 rounded-full bg-fjord-blue mt-1.5 shrink-0" />
                              <span className="text-midnight-abyss font-medium leading-relaxed">
                                {task.task}
                              </span>
                            </div>
                            <div className="flex items-center gap-1 shrink-0">
                              <span className={`badge text-2xs border ${priorityBadges[task.priority] || priorityBadges.Medium}`}>
                                {task.priority}
                              </span>
                              <span className="text-2xs text-frosty-slate flex items-center gap-0.5">
                                <Clock className="w-2.5 h-2.5" />
                                {task.timeEstimate}
                              </span>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>

                    <div className="pt-3 border-t border-glacial-sky/30 text-xs text-midnight-abyss flex items-start gap-2 bg-white/60 p-2.5 rounded-xl">
                      <Target className="w-4 h-4 text-emerald-600 shrink-0 mt-0.5" />
                      <div>
                        <strong className="text-midnight-abyss">Milestone Benchmark: </strong>
                        <span className="text-frosty-slate">{weekData.milestone}</span>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Strategic Success Tip */}
            {result.successTip && (
              <div className="card p-6 border-glacial-sky/30 bg-white">
                <h4 className="font-heading font-bold text-lg text-midnight-abyss mb-2 flex items-center gap-2">
                  <Sparkles className="w-5 h-5 text-fjord-blue" />
                  <span>Strategic Creator Tip</span>
                </h4>
                <p className="text-sm text-midnight-abyss leading-relaxed">
                  {result.successTip}
                </p>
              </div>
            )}

            {/* Product Conversion Loop */}
            <div className="p-6 rounded-2xl bg-gradient-to-r from-[#223354] to-[#4A6D99] text-white flex flex-col md:flex-row items-center justify-between gap-5 shadow-card">
              <div>
                <span className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-white/15 text-[#FADADD] mb-2">
                  <Zap className="w-3.5 h-3.5" />
                  Week 1 Implementation
                </span>
                <h4 className="font-heading font-bold text-xl text-white">
                  Ready to Script Your Next Video?
                </h4>
                <p className="text-glacial-sky text-xs md:text-sm mt-1 max-w-xl">
                  Generate 20 high-converting hooks tailored to Week 1 objectives.
                </p>
              </div>
              <Link
                to="/hook-generator"
                className="inline-flex items-center gap-2 px-5 py-3 rounded-xl font-bold text-midnight-abyss bg-white hover:bg-glacial-sky transition-colors text-sm shrink-0 shadow-md"
              >
                <span>Generate Week 1 Hooks</span>
                <ArrowRight className="w-4 h-4 text-fjord-blue" />
              </Link>
            </div>
          </motion.div>
        )}

        {/* Default State: FAQ */}
        {!result && !isLoading && (
          <div className="space-y-12 mt-4">
            <AdBanner />

            <div>
              <h2 className="font-heading font-bold text-2xl text-midnight-abyss mb-6 text-center">
                Frequently Asked Questions
              </h2>
              <div className="space-y-4 max-w-3xl mx-auto">
                {FAQ.map((item, i) => (
                  <div key={i} className="card p-5 border-glacial-sky/30">
                    <h3 className="font-semibold text-midnight-abyss mb-2 flex items-center gap-2">
                      <HelpCircle className="w-4 h-4 text-fjord-blue shrink-0" />
                      <span>{item.q}</span>
                    </h3>
                    <p className="text-frosty-slate text-sm leading-relaxed pl-6">
                      {item.a}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>
    </>
  );
}
